main:
  - name: Research
    url: '#research'
    weight: 10
  - name: Agenda
    url: '#agenda'
    weight: 20
  - name: Join Us
    url: '#hiring'
    weight: 25
  - name: Publications
    url: publication
    weight: 30
  - name: People
    url: people
    weight: 40
  - name: Contact
    url: contact
    weight: 50
