main:
  - name: Research
    url: '#research'
    weight: 10
  - name: Agenda
    url: '#agenda'
    weight: 20
  - name: Join Us
    url: '#hiring'
    weight: 25
  - name: Outputs
    url: outputs
    weight: 30
  - name: Contact
    url: contact
    weight: 50
